- name: upgrade all packages
  become: yes
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600

- name: install packages
  become: yes
  apt:
    name: '{{ item }}'
  with_items:
    - avahi-daemon
    - vim
    - htop
    - git

- name: set locale
  become: yes
  command: localectl set-locale LANG=en_US.UTF-8

- name: set timezone
  become: yes
  timezone:
    name: UTC

- name: allow users in sudo group to use sudo command without password
  become: yes
  lineinfile:
    path: /etc/sudoers
    regexp: '^%sudo\s+ALL=\(ALL:ALL\) (NOPASSWD: )?ALL'
    line: '%sudo  ALL=(ALL:ALL) NOPASSWD: ALL'
    validate: /usr/sbin/visudo -cf %s

- name: create workspace
  file:
    path: '{{ ansible_env.HOME }}/workspace'
    state: directory

- name: clone arosh/dotfiles
  git:
    repo: https://github.com/arosh/dotfiles.git
    dest: '{{ ansible_env.HOME }}/workspace/dotfiles'

- name: link .vimrc
  file:
    path: '{{ ansible_env.HOME }}/.vimrc'
    state: link
    src: '{{ ansible_env.HOME }}/workspace/dotfiles/.vimrc.tiny'
