- name: replace /etc/apt/sources.list
  become: yes
  copy:
    dest: /etc/apt/sources.list
    content: |
      deb http://ftp.iij.ad.jp/pub/linux/ubuntu/archive/ {{ ansible_lsb.codename }} main restricted universe
      deb http://ftp.iij.ad.jp/pub/linux/ubuntu/archive/ {{ ansible_lsb.codename }}-updates main restricted universe
      deb http://ftp.iij.ad.jp/pub/linux/ubuntu/archive/ {{ ansible_lsb.codename }}-security main restricted universe

- name: update APT cache
  become: yes
  apt:
    update_cache: yes

- name: install packages
  become: yes
  apt:
    name:
      - avahi-daemon
      - vim
      - htop
      - git
      - apt-file

- name: check if the host is running on Hyper-V
  command: /usr/bin/systemd-detect-virt
  register: virt
  check_mode: no
  changed_when: false

- debug: var=virt.stdout

# https://docs.microsoft.com/ja-jp/windows-server/virtualization/hyper-v/supported-ubuntu-virtual-machines-on-hyper-v
- name: install linux-azure on Hyper-V
  become: yes
  apt:
    name: 'linux-azure'
  when: virt.stdout == 'microsoft'

- name: uninstall packages
  become: yes
  apt:
    name:
      - snapd
      - nano
      - unattended-upgrades
    state: absent
    purge: yes
    autoremove: yes

- name: upgrade all packages
  become: yes
  apt:
    upgrade: dist
  when: not ansible_env['GITHUB_ACTIONS']

- name: set locale
  become: yes
  command: localectl set-locale LANG=en_US.UTF-8

- name: set timezone
  become: yes
  timezone:
    name: UTC

- name: allow users in sudo group to use sudo command without password
  become: yes
  lineinfile:
    path: /etc/sudoers
    regexp: '^%sudo\s+ALL=\(ALL:ALL\) (NOPASSWD: )?ALL'
    line: '%sudo  ALL=(ALL:ALL) NOPASSWD: ALL'
    validate: /usr/sbin/visudo -cf %s

- name: create workspace
  file:
    path: '{{ ansible_user_dir }}/workspace'
    state: directory

- name: clone arosh/dotfiles
  git:
    repo: https://github.com/arosh/dotfiles.git
    dest: '{{ ansible_user_dir }}/workspace/dotfiles'

- name: link .vimrc
  file:
    path: '{{ ansible_user_dir }}/.vimrc'
    state: link
    src: '{{ ansible_user_dir }}/workspace/dotfiles/.vimrc.tiny'
