- name: upgrade all packages
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600

- name: set locale
  command: localectl set-locale LANG=C.UTF-8

- name: set timezone
  command: timedatectl set-timezone UTC

- name: allow users in sudo group to use sudo command without password
  lineinfile:
    path: /etc/sudoers
    regexp: '^%sudo\s+ALL=\(ALL:ALL\) (NOPASSWD: )?ALL'
    line: '%sudo  ALL=(ALL:ALL) NOPASSWD: ALL'
    validate: /usr/sbin/visudo -cf %s

- name: install avahi-daemon
  apt:
    name: '{{ item }}'
  with_items:
    - avahi-daemon
    - vim

- name: download .vimrc
  become_user: '{{ username }}'
  get_url:
    url: https://raw.githubusercontent.com/arosh/dotfiles/master/.vimrc
    dest: /home/{{ username }}/.vimrc
