- name: upgrade all packages
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600

- name: install packages
  apt:
    name: '{{ item }}'
  with_items:
    - avahi-daemon
    - vim
    - htop
    - git

- name: set locale
  command: localectl set-locale LANG=C.UTF-8

- name: set timezone
  command: timedatectl set-timezone UTC

- name: allow users in sudo group to use sudo command without password
  lineinfile:
    path: /etc/sudoers
    regexp: '^%sudo\s+ALL=\(ALL:ALL\) (NOPASSWD: )?ALL'
    line: '%sudo  ALL=(ALL:ALL) NOPASSWD: ALL'
    validate: /usr/sbin/visudo -cf %s

- name: create workspace
  become_user: '{{ username }}'
  file:
    path: /home/{{ username }}/workspace
    state: directory

- name: clone arosh/dotfiles
  become_user: '{{ username }}'
  git:
    repo: https://github.com/arosh/dotfiles.git
    dest: /home/{{ username }}/workspace/dotfiles

- name: link .vimrc
  become_user: '{{ username }}'
  file:
    path: /home/{{ username }}/.vimrc
    state: link
    src: /home/{{ username }}/workspace/dotfiles/.vimrc.tiny
