name: Run Ansible

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install ansible
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y ansible
    - name: create inventory
      run: |
        cat > hosts <<EOF
        localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3
        EOF
    - name: run ansible
      run: make
